#!/usr/bin/env python
# coding: utf-8

# In[ ]:


"""
This model is output by TPOT and should be used to predict likelihood of readmission
input: EMR data with all features engineered during training period appended
output: 'scored' data: unique patient identifier ['patient_id'] and readmission_likely (0/1);
        features contributing to likelihood saved to Mongo for future use

author: Andrew Malinow, PhD
last updated: 2/26/20
"""


# In[ ]:


"""
Imports
libraries will vary from customer to customer and are automatically generated by TPOT
Libraries below are for Readmission
"""
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split


# In[ ]:


"""
net-new data [emr data not used in training the model]
"""
new_data="insert a 1000 record sample of data for testing"


# In[ ]:


"""
Process new data with TPOT model
"""
#new_data is any record entered after the training period, which have had the additional engineered features appended
#and categorical values have been one-hot-encoded.  
exported_pipeline = RandomForestClassifier(bootstrap=False, criterion="entropy", max_features=0.8500000000000001, min_samples_leaf=2, min_samples_split=10, n_estimators=100)
results = exported_pipeline.predict(new_data)

